### ISSUE TITLE
Multiple tabs updating

### ISSUE THREAD

**Issue by nanotane** [eliskin/ColorFriendly#7]
We have the problem that when a user changes their setting we can't get all of the tabs to update their settings. This is because the background page can only communicate with the most recently open page. It looks like the problem stems from the fact that the content scripts that communicate with the background page all use the same communication port. So when a new one tab is made, it connects with the background script through that port and background.js then is only communicating with that one content script. We need a way for the background script to keep track of all the content script communication ports. So each content script needs its own unique port and background needs to keep track of that.

**Comment by pcali41** [comment]
This issue has been resolved in pull request #10. The background script can now broadcast new settings changes to all tabs automatically getting rid of the need to keep track of unique port connections to update the pages.
